# Generated by Django 2.1.2 on 2019-02-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190212_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='balance_type',
        ),
        migrations.RemoveField(
            model_name='record',
            name='description',
        ),
    ]
