# Generated by Django 2.1.2 on 2019-02-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190215_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='cnt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
